# ============================================
# CONFIGURACIÓN MONGODB LOCAL
# ============================================
spring.data.mongodb.uri=mongodb://localhost:27017/jlg_aislamientos

# ============================================
# CONFIGURACIÓN DE THYMELEAF
# ============================================
spring.thymeleaf.cache=false

# ============================================
# PUERTO DEL SERVIDOR
# ============================================
server.port=8083

# Nombre personalizado de la cookie
server.servlet.session.cookie.name=JLG_SESSION_ID

# Proteger contra XSS (¿true o false?)
server.servlet.session.cookie.http-only=TRUE

# Permitir HTTP local (¿true o false?)
server.servlet.session.cookie.secure=FALSE

# Tiempo de expiración de la sesión en segundos (Ej. 1800 = 30 minutos)
server.servlet.session.timeout=1800