# ============================================
# CONFIGURACIÓN MONGODB LOCAL
# ============================================
spring.data.mongodb.uri=mongodb://localhost:27017/jlg_aislamientos

# ============================================
# CONFIGURACIÓN DE THYMELEAF
# ============================================
spring.thymeleaf.cache=false

# ============================================
# PUERTO DEL SERVIDOR
# ============================================
server.port=8083